# Generated by Django 4.1 on 2022-11-25 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("controle", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tabela",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateTimeField(auto_now=True)),
                ("quantidade", models.IntegerField(max_length=10)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=7)),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="controle.produtos",
                    ),
                ),
            ],
        ),
    ]
