# Generated by Django 4.1 on 2022-11-25 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controle", "0002_tabela"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tabela",
            name="data",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
