# Generated by Django 4.1 on 2022-11-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controle", "0004_alter_tabela_quantidade_transacao"),
    ]

    operations = [
        migrations.CreateModel(
            name="Estoque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=100)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=7)),
                ("quantidade", models.IntegerField()),
                ("data", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
