# Generated by Django 4.1.3 on 2022-12-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0005_estoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='descrição',
            field=models.TextField(max_length=100),
        ),
    ]
